name: CI

on: [push, pull_request]

jobs:
  ci:
    name: Node ${{ matrix.node_version }}

    strategy:
      fail-fast: false
      matrix:
        node_version: [8, 10, 12, 13]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.3
    - name: Use Node ${{ matrix.node_version }}
      uses: actions/setup-node@v2.1.1
      with:
        node_version: ${{ matrix.node_version }}
    - name: Install
      run: yarn install --pure-lockfile
    - name: Build
      run: yarn code:build
    - name: Lint
      run: yarn lint
    - name: Test
      run: yarn test
